# package mirror: https://php-package-mirror.scrutinizer-ci.com/$VER.tar.bz2 
build:
  image: default-bionic
  environment:
    php:
      version: 8.3.3
      ini:
        xdebug.mode: coverage
    node:
      version: 14.17.6
  nodes:
    analysis:
      dependencies:
        before:
          - 'sudo git clone https://github.com/grommunio/mapi-header-php.git /usr/share/php-mapi'
      environment:
        node: 14.17.6
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
    tests:
      dependencies:
        before:
          - 'sudo git clone https://github.com/grommunio/mapi-header-php.git /usr/share/php-mapi'
filter:
  excluded_paths:
    - "*/build/**"
    - "*/vendor/**"
    - "*.min.js"
    - "*.tpl.php"
    - "client/dompurify/**"
    - "client/tinymce/**"
    - "client/filepreviewer/pdfjs/**"
    - "client/filepreviewer/ViewerJS/**"
    - "plugins/files/php/Files/Backend/Webdav/sabredav/**"
checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - phpunit/phpunit
tools:
  php_cs_fixer:
    config: .phpcs
