Ext.namespace('Zarafa.hierarchy.ui');

/**
 * @class Zarafa.hierarchy.ui.HierarchyFolderDropZone
 * @extends Zarafa.hierarchy.ui.HierarchyTreeDropZone
 *
 * Specialized {@link Ext.tree.TreeDropZone Drop Zone} which
 * is used for dragging and dropping {@link Zarafa.hierarchy.data.MAPIFolderRecord folders}
 * in the {@link Zarafa.hierarchy.ui.HierarchyTreePanel Hierarchy Tree}.
 */
Zarafa.hierarchy.ui.HierarchyFolderDropZone = Ext.extend(Zarafa.hierarchy.ui.HierarchyTreeDropZone, {

	/**
	 * @constructor
	 * @param {String/HTMLElement/Element} tree The {@link Ext.tree.TreePanel} for which to enable dropping
	 * @param {Object} config
	 */
	constructor: function(tree, config)
	{
		Zarafa.hierarchy.ui.HierarchyFolderDropZone.superclass.constructor.call(this, tree, config);

		if (this.tree) {
			this.tree.on('beforenodedrop', this.onBeforeNodeDrop, this);
		}
	},

	/**
	 * Event handler for the {@link Ext.tree.TreePanel#beforenodedrop 'beforenodedrop'}
	 * event which is fired just before a node is being dropped. This will check if we
	 * are dropping the folder on the same parent as it is currently in already. When
	 * this happens we cancel the drop. This ensures that the UI will complete the drop
	 * just as if everything worked as expected.
	 *
	 * @param {Object} dropEvent The event object which describes what node is being
	 * dropped where.
	 * @private
	 */
	onBeforeNodeDrop: function(dropEvent)
	{
		var dropNode = dropEvent.dropNode;

		if (Ext.isDefined(dropNode)) {
			// Reordering the mailboxes is a drop between siblings by definition: every
			// mailbox hangs off the same (invisible) root node. So it must be exempt from
			// the same-parent check below, which exists for folders being moved.
			if (Zarafa.hierarchy.ui.HierarchyFolderDropZone.isStoreReorderDrop(dropEvent)) {
				return;
			}

			var targetNode = dropEvent.target;

			switch (dropEvent.point) {
				case 'above':
				case 'below':
					targetNode = targetNode.parentNode;
					break;
				case 'append':
				/* falls through */
				default:
					break;
			}

			// Is dropped on same parent, cancel drop event
			if (dropNode.parentNode === targetNode) {
				return false;
			}
		}
	},

	/**
	 * Obtain the DropPoint string ('above', 'append' and 'below') which
	 * indicate at which position we are currently dragging the object
	 * over the current node.
	 *
	 * This code is copied from the superclass, with the only exception
	 * that it will allow the 'append' string even though the folder
	 * over which we are hovering is a leaf node.
	 *
	 * @param {Ext.EventObj} e The Event Object used for dragging the item
	 * @param {Object} n The object which describes the node over which
	 * the item is being hovered
	 * @parmam {Ext.tree.TreeDragZone} dd The DragZone which is used
	 * for dragging the current item
	 * @private
	 */
	getDropPoint: function(e, n, dd)
	{
		var tn = n.node;
		var dragNode = dd && dd.dragData ? dd.dragData.node : undefined;

		if (tn.isRoot) {
			return tn.allowChildren !== false ? 'append' : false; // always append for root
		}
		var dragEl = n.ddel;

		// A mailbox is dropped between mailboxes, never into one, so it has no 'append'
		// point. Split the node in half instead of in thirds, which the code below does
		// to leave room for 'append' - otherwise the middle of every row would be dead.
		// Kept below the isRoot check above: the root node's UI has no 'elNode', so
		// reading its geometry would throw.
		if (Zarafa.hierarchy.ui.HierarchyFolderDropZone.isReorderableNode(dragNode)) {
			var middle = Ext.lib.Dom.getY(dragEl) + (dragEl.offsetHeight / 2);
			return Ext.lib.Event.getPageY(e) < middle ? 'above' : 'below';
		}

		var t = Ext.lib.Dom.getY(dragEl), b = t + dragEl.offsetHeight;
		var y = Ext.lib.Event.getPageY(e);
		var noAppend = tn.allowChildren === false;
		if (this.appendOnly || tn.parentNode.allowChildren === false) {
			return noAppend ? false : 'append';
		}
		var noBelow = false;
		if (!this.allowParentInsert) {
			noBelow = tn.hasChildNodes() && tn.isExpanded();
		}
		var q = (b - t) / (noAppend ? 2: 3);
		if (y >= t && y < (t + q)) {
			return 'above';
		} else if (!noBelow && (noAppend || y >= b-q && y <= b)) {
			return 'below';
		} else {
			return 'append';
		}
	},

	/**
	 * Called by {@link #processDrop} to perform the final step of of dropping the item.
	 * This will call the {@link #folderdrop} event.
	 *
	 * @param {Object} de The dropEvent as generated by {@link #processDrop}.
	 * @private
	 */
	completeDrop: function(de)
	{
		de.target.ui.endDrop();
		this.tree.fireEvent("folderdrop", de);
	},

	/**
	 * Function which return false when the dragged record is hovering over
	 * the {@link Zarafa.hierarchy.data.MAPIFolderRecord#isDropTargetForFolders special} folders.
	 *
	 * @param {Object} n The object which describes the node over which
	 * the item is being hovered
	 * @param {String} pt The DropPoint (see {@link #getDropPoint}).
	 * @param {Ext.tree.TreeDragZone} dd The DragZone which is used
	 * for dragging the current item
	 * @param {Ext.EventObject} e The Event Object used for dropping the item
	 * @param {Object} data The data object describing the {@link Zarafa.hierarchy.ui.FolderNode folder} node Item which
	 * are being dragged
	 * @private
	 */
	isValidDropPoint: function(n, pt, dd, e, data)
	{
		var targetNode = n ? n.node : undefined;
		var dropNode = data ? data.node : undefined;
		var zone = Zarafa.hierarchy.ui.HierarchyFolderDropZone;

		if (!targetNode || !Ext.isFunction(targetNode.getFolder)) {
			return false;
		}

		// A top level node stands for a mailbox, so dragging one can only ever mean moving
		// that mailbox to another position - never a folder move, even in a filtered tree
		// where the node happens to be an ordinary folder. It may therefore only be
		// dropped between other mailboxes which the user is allowed to reorder, and never
		// appended into a folder, which would read as "move this mailbox into that folder"
		// and has no meaning.
		if (zone.isTopLevelNode(dropNode)) {
			if (!zone.isReorderableNode(dropNode) || !zone.isReorderableNode(targetNode)) {
				return false;
			}

			if (pt !== 'above' && pt !== 'below') {
				return false;
			}

			return zone.superclass.isValidDropPoint.apply(this, arguments);
		}

		var folder = targetNode.getFolder();
		if (folder.isDropTargetForFolders() === false) {
			return false;
		}

		// Dropping a folder above or below the root node of a store means dropping it
		// into that node's parent, which is the invisible root node of the hierarchy -
		// not a folder at all. The drop was accepted and then failed in the move
		// handler, which reads 'target.getFolder()' on a node that has no such method.
		if ((pt === 'above' || pt === 'below') && !targetNode.parentNode.getFolder) {
			return false;
		}

		return zone.superclass.isValidDropPoint.apply(this, arguments);
	}
});

Ext.apply(Zarafa.hierarchy.ui.HierarchyFolderDropZone, {
	/**
	 * Check if the given tree node sits at the top level of the hierarchy, i.e. directly
	 * below the invisible root node. Which folder that is depends on the tree: in an
	 * unfiltered tree it is the IPM_SUBTREE of a store, but in a filtered tree - the
	 * calendar folder list, for instance - the IPM_SUBTREE of a shared store is left out
	 * and its visible folders are lifted to the top level instead
	 * (see {@link Zarafa.hierarchy.data.HierarchyTreeLoader#directFn}).
	 * @param {Ext.tree.TreeNode} node The node to check
	 * @return {Boolean} True when the node is a top level node of the hierarchy
	 * @static
	 */
	isTopLevelNode: function(node)
	{
		if (!node || !Ext.isFunction(node.getFolder) || !node.getFolder()) {
			return false;
		}

		if (!node.parentNode) {
			return false;
		}

		return node.parentNode.isRoot === true;
	},

	/**
	 * Check if the given tree node stands for a mailbox whose position in the hierarchy
	 * the user is allowed to change. In a filtered tree several nodes can stand for the
	 * same mailbox, one per visible folder; each of them may be dragged and they move
	 * the mailbox as a whole.
	 * @param {Ext.tree.TreeNode} node The node to check
	 * @return {Boolean} True when dragging the node reorders the mailboxes
	 * @static
	 */
	isReorderableNode: function(node)
	{
		if (!this.isTopLevelNode(node)) {
			return false;
		}

		return Zarafa.hierarchy.data.StoreOrder.isReorderable(node.getFolder().getMAPIStore());
	},

	/**
	 * Check if the given drop event describes a mailbox being moved to a new position in
	 * the hierarchy, as opposed to a folder being moved or copied. A drop onto another
	 * node of the same mailbox is not a reorder - there is nothing to move.
	 * @param {Object} dropEvent The event object which describes what node is being dropped where
	 * @return {Boolean} True when the drop reorders the mailboxes
	 * @static
	 */
	isStoreReorderDrop: function(dropEvent)
	{
		if (dropEvent.point !== 'above' && dropEvent.point !== 'below') {
			return false;
		}

		if (!this.isReorderableNode(dropEvent.dropNode) || !this.isReorderableNode(dropEvent.target)) {
			return false;
		}

		var storeOrder = Zarafa.hierarchy.data.StoreOrder;
		return storeOrder.getStoreKey(dropEvent.dropNode.getFolder().getMAPIStore()) !==
			storeOrder.getStoreKey(dropEvent.target.getFolder().getMAPIStore());
	}
});
