/*
 * SPDX-FileCopyrightText: Copyright 2020 - 2026 grommunio GmbH
 * SPDX-FileCopyrightText: Copyright 2016 Kopano and its licensors
 * SPDX-FileCopyrightText: Copyright 2005 - 2016 Zarafa B.V. and its licensors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

Ext.namespace('Grommunio.core');

/**
 * @class Grommunio.core.ErrorType
 * @extends Grommunio.core.Enum
 *
 * @singleton
 */
Grommunio.core.ErrorType = Grommunio.core.Enum.create({
	/**
	 * Denotes type of error is MAPI which is generated from an erroneous mapi call.
	 * @property
	 * @type Number
	 */
	'MAPI': 1,

	/**
	 * Denotes type of error is GROMMUNIO which is generated by our PHP code.
	 * @property
	 * @type Number
	 */
	'GROMMUNIO': 2,

	/**
	 * Denotes type of error is GENERAL which is generated by PHP's error handler.
	 * @property
	 * @type Number
	 */
	'GENERAL': 3
});

