Ext.namespace('Grommunio.core');

/**
 * @class Grommunio.core.ErrorType
 * @extends Grommunio.core.Enum
 *
 * @singleton
 */
Grommunio.core.ErrorType = Grommunio.core.Enum.create({
	/**
	 * Denotes type of error is MAPI which is generated from an erroneous mapi call.
	 * @property
	 * @type Number
	 */
	'MAPI': 1,

	/**
	 * Denotes type of error is GROMMUNIO which is generated by our PHP code.
	 * @property
	 * @type Number
	 */
	'GROMMUNIO': 2,

	/**
	 * Denotes type of error is GENERAL which is generated by PHP's error handler.
	 * @property
	 * @type Number
	 */
	'GENERAL': 3
});

