<?php

/**
 * Webapp-specific security policy for the shared KeyCloak client.
 */
class WebAppKeyCloak extends KeyCloak {
	private const MAX_PENDING_STATES = 8;
	private const STATE_LIFETIME = 600;
	private const STATE_SESSION_KEY = '_keycloak_oauth_states';

	/** @var null|self */
	private static $instance;

	/**
	 * Use a configured callback URL, or derive one without trusting Host and
	 * Request-URI headers supplied by the client.
	 *
	 * @param mixed $keycloakConfig decoded keycloak.json configuration
	 */
	public function __construct(mixed $keycloakConfig) {
		if (is_string($keycloakConfig)) {
			$keycloakConfig = json_decode($keycloakConfig, true);
		}
		if (!is_array($keycloakConfig)) {
			$keycloakConfig = [];
		}
		foreach (['realm', 'resource', 'redirect-url', 'realm-public-key', 'secret'] as $stringKey) {
			if (isset($keycloakConfig[$stringKey]) && !is_string($keycloakConfig[$stringKey])) {
				throw new InvalidArgumentException('Invalid Keycloak configuration value');
			}
		}
		if (isset($keycloakConfig['public-client']) && !is_bool($keycloakConfig['public-client'])) {
			throw new InvalidArgumentException('Invalid Keycloak public-client setting');
		}
		if (isset($keycloakConfig['credentials'])) {
			if (!is_array($keycloakConfig['credentials']) ||
				(isset($keycloakConfig['credentials']['secret']) && !is_string($keycloakConfig['credentials']['secret']))) {
				throw new InvalidArgumentException('Invalid Keycloak credentials');
			}
		}
		$authServerUrl = $keycloakConfig['auth-server-url'] ?? null;
		if (!is_string($authServerUrl) || filter_var($authServerUrl, FILTER_VALIDATE_URL) === false) {
			throw new InvalidArgumentException('Invalid Keycloak server URL');
		}
		$redirectUrl = self::callbackUrl($keycloakConfig);
		if ($redirectUrl === null) {
			throw new UnexpectedValueException('No valid Keycloak callback URL is configured');
		}
		// Older mapi-header releases access this optional key without a default.
		if (($keycloakConfig['public-client'] ?? false) && !isset($keycloakConfig['realm-public-key'])) {
			$keycloakConfig['realm-public-key'] = '';
		}

		parent::__construct($keycloakConfig);
		$this->redirect_url = $redirectUrl;
	}

	/**
	 * Return the webapp Keycloak singleton configured by keycloak.json.
	 */
	public static function getInstance(): ?WebAppKeyCloak {
		if (!defined('GROMOX_CONFIG_PATH')) {
			define('GROMOX_CONFIG_PATH', '/etc/gromox/');
		}

		$configFile = GROMOX_CONFIG_PATH . 'keycloak.json';
		if (self::$instance === null && is_file($configFile)) {
			$configJson = @file_get_contents($configFile);
			if ($configJson === false) {
				error_log('Unable to load webapp Keycloak configuration');

				return null;
			}
			$config = json_decode($configJson, true);
			if (!is_array($config)) {
				error_log('Unable to load webapp Keycloak configuration');

				return null;
			}

			try {
				self::$instance = new self($config);
			}
			catch (InvalidArgumentException|UnexpectedValueException) {
				error_log('Unable to load webapp Keycloak configuration');

				return null;
			}
		}

		return self::$instance;
	}

	/**
	 * Build an authorization URL and remember its one-time state value.
	 *
	 * The argument remains for compatibility with KeyCloak::login_url(); the
	 * validated callback established by the constructor is always used.
	 *
	 * @param string $redirectUrl ignored caller-supplied redirect URL
	 * @param bool   $usePkce     ignored parent-client compatibility option
	 *
	 * @return string authorization URL
	 */
	public function login_url($redirectUrl, $usePkce = false): string {
		$state = bin2hex(random_bytes(32));
		$this->storeState($state);

		$params = [
			'scope' => 'openid',
			'client_id' => $this->client_id,
			'state' => $state,
			'redirect_uri' => $this->redirect_url,
			'response_type' => 'code',
		];

		return $this->realm_url . '/protocol/openid-connect/auth?' . http_build_query($params, '', '&', PHP_QUERY_RFC3986);
	}

	/**
	 * Consume a current state value exactly once.
	 *
	 * @param mixed $state callback state parameter
	 *
	 * @return bool true when the state was generated by this session
	 */
	public function consumeState($state) {
		$states = $this->pendingStates();
		if (!is_string($state) || preg_match('/\A[a-f0-9]{64}\z/D', $state) !== 1) {
			$this->saveStates($states);

			return false;
		}

		$key = hash('sha256', $state);
		if (!isset($states[$key])) {
			$this->saveStates($states);

			return false;
		}

		unset($states[$key]);
		$this->saveStates($states);

		return true;
	}

	/**
	 * Require the introspection endpoint to return the JSON boolean true.
	 *
	 * @param mixed $token access token
	 */
	protected function validate_token(mixed $token): bool {
		if (!isset($token)) {
			return false;
		}

		$headers = ['Content-Type: application/x-www-form-urlencoded'];
		$params = ['token' => $token->get_payload()];
		if ($this->is_public) {
			$params['client_id'] = $this->client_id;
		}
		else {
			$headers[] = 'Authorization: Basic ' . base64_encode($this->client_id . ':' . $this->secret);
		}

		$response = $this->http_curl_request(
			'POST',
			'/protocol/openid-connect/token/introspect',
			$headers,
			http_build_query($params)
		);
		if ($response['code'] < 200 || $response['code'] > 299) {
			return false;
		}

		try {
			$data = json_decode((string) $response['body'], true, 512, JSON_THROW_ON_ERROR);
		}
		catch (JsonException) {
			return false;
		}

		return is_array($data) && !array_key_exists('error', $data) && ($data['active'] ?? null) === true;
	}

	/**
	 * Choose and normalize the OAuth callback URL.
	 *
	 * SERVER_NAME is expected to be fixed by the web-server configuration.
	 * Deployments which derive it from Host must set redirect-url explicitly.
	 *
	 * @param array $config keycloak.json configuration
	 *
	 * @return null|string
	 */
	private static function callbackUrl($config) {
		if (isset($config['redirect-url'])) {
			return self::normalizeCallbackUrl($config['redirect-url']);
		}

		$serverName = (string) ($_SERVER['SERVER_NAME'] ?? '');
		$scriptName = (string) ($_SERVER['SCRIPT_NAME'] ?? '/index.php');
		$scriptName = preg_replace('/[\x00-\x1f\x7f]/', '', str_replace('\\', '/', $scriptName));
		$scriptName = '/' . ltrim($scriptName, '/');
		// OAuth callbacks are handled by the HTML entry point. Refresh can run
		// from grommunio.php, so retain its deployment directory, not its name.
		if (strtolower(basename($scriptName)) !== 'index.php') {
			$scriptName = rtrim(dirname($scriptName), '/') . '/index.php';
		}

		return self::normalizeCallbackUrl('https://' . $serverName . $scriptName);
	}

	/**
	 * Normalize an absolute HTTPS callback URL.
	 *
	 * @param mixed $url
	 *
	 * @return null|string
	 */
	private static function normalizeCallbackUrl($url) {
		if (!is_string($url) || $url === '' || strlen($url) > 4096 ||
			preg_match('/[\x00-\x20\x5c\x7f]/', $url) === 1) {
			return null;
		}

		$parts = @parse_url($url);
		if ($parts === false || strtolower($parts['scheme'] ?? '') !== 'https' || empty($parts['host']) ||
			isset($parts['user']) || isset($parts['pass']) || isset($parts['fragment'])) {
			return null;
		}

		$host = trim(strtolower((string) $parts['host']), '[]');
		if (filter_var($host, FILTER_VALIDATE_IP) === false) {
			$host = rtrim($host, '.');
			if ($host === '' || strlen($host) > 253 || preg_match('/\A[0-9.]+\z/D', $host) === 1 ||
				preg_match('/\A(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)(?:\.(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?))*\z/D', $host) !== 1) {
				return null;
			}
		}

		$port = $parts['port'] ?? 443;
		if (!is_int($port) || $port < 1 || $port > 65535) {
			return null;
		}

		$authority = str_contains($host, ':') ? '[' . $host . ']' : $host;
		if ($port !== 443) {
			$authority .= ':' . $port;
		}
		$path = $parts['path'] ?? '/';
		if ($path === '') {
			$path = '/';
		}
		$query = isset($parts['query']) ? '?' . $parts['query'] : '';

		return 'https://' . $authority . $path . $query;
	}

	/**
	 * Store a state value and retain a small set for concurrent login tabs.
	 *
	 * @param string $state
	 */
	private function storeState($state) {
		$states = $this->pendingStates();
		$states[hash('sha256', $state)] = time() + self::STATE_LIFETIME;
		asort($states, SORT_NUMERIC);
		if (count($states) > self::MAX_PENDING_STATES) {
			$states = array_slice($states, -self::MAX_PENDING_STATES, null, true);
		}
		$this->saveStates($states);
	}

	/**
	 * Return pending, unexpired state hashes from the session.
	 *
	 * @return array<string, int>
	 */
	private function pendingStates() {
		$stored = $_SESSION[self::STATE_SESSION_KEY] ?? [];
		if (!is_array($stored)) {
			return [];
		}

		$states = [];
		$now = time();
		foreach ($stored as $hash => $expires) {
			if (is_string($hash) && preg_match('/\A[a-f0-9]{64}\z/D', $hash) === 1 &&
				is_int($expires) && $expires >= $now) {
				$states[$hash] = $expires;
			}
		}

		return $states;
	}

	/**
	 * Save pending states, removing the session key when none remain.
	 *
	 * @param array $states
	 */
	private function saveStates($states) {
		if (empty($states)) {
			unset($_SESSION[self::STATE_SESSION_KEY]);
		}
		else {
			$_SESSION[self::STATE_SESSION_KEY] = $states;
		}
	}
}
